---
title: "C28198 | Документы Microsoft"
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: a930019b1f7369f1d6035eef4f467d0fe17c6732
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/22/2017
---
# <a name="c28198"></a>C28198
Предупреждение C28198: возможна утечка памяти из-за исключения.  
  
 Это предупреждение указывает, что выделенная память не освобождается после возникновения исключения. Оператор в конце пути может вызвать исключение. Объем памяти был передан в функцию, которая будет сохранена копия освобождаемой позже.  
  
 Это предупреждение очень похож на предупреждение [C28197](../code-quality/c28197.md). Заметки, которые рекомендуются для использования с предупреждением [C28197](../code-quality/c28197.md) также может использоваться здесь.  
  
## <a name="example"></a>Пример  
 Следующий пример кода вызывает появление этого предупреждения.  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 Следующий пример кода позволяет избежать появления этого предупреждения.  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```